export enum ActionType { // to do not repeat action types strings
    SEARCH_REPOSITORIES = 'SEARCH_REPOSITORIES',
    SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS',
    SEARCH_REPOSITORIES_ERROR = 'SEARCH_REPOSITORIES_ERROR'
}

